"""Phase 1.2: Code Generation

Generates deterministic Python extraction code from pattern analysis.

Takes the patterns identified by the analyzer and generates:
- Python functions for field extraction
- Regex patterns for value matching
- Validation rules
- Error handling

Output: Self-contained Python module (extractors_v<N>.py) with standard interface
"""
import logging
import json
import hashlib
from typing import Dict, Any, Optional
from datetime import datetime, timezone
from llm_service import get_llm_client
import config

logger = logging.getLogger(__name__)


def generate_extractors(analysis: Dict[str, Any],
                       schema_fields: list = config.SCHEMA_FIELDS) -> Dict[str, Any]:
    """Generate Python extraction code from pattern analysis.

    Args:
        analysis: Output from Phase 1 analyzer
        schema_fields: Target fields to extract

    Returns:
        Generated extractor code and metadata
    """
    if analysis.get("status") != "success":
        raise ValueError(f"Invalid analysis result: {analysis.get('status')}")

    llm = get_llm_client()

    # Build code generation prompt
    schema_str = json.dumps(schema_fields, indent=2)
    analysis_str = json.dumps(analysis.get("analysis", {}), indent=2)

    system_prompt = """You are an expert Python developer. Generate clean, efficient,
deterministic extraction code that:
1. Extracts specified fields from documents
2. Handles edge cases gracefully
3. Returns JSON-structured output
4. Has no side effects (pure functions)
5. Includes helpful docstrings and type hints

Code should be production-ready and executable."""

    user_prompt = f"""Based on this pattern analysis, generate Python extraction functions.

Target fields to extract:
{schema_str}

Pattern analysis:
{analysis_str}

Generate Python code with:
1. Function: extract_pii(title: str, body_text: str) -> dict
   - Returns dict with extracted fields (None for missing fields)
   - Includes confidence scores where applicable

2. Helper functions:
   - extract_emails(text: str) -> list[str]
   - extract_phone_numbers(text: str) -> list[str]
   - extract_names(text: str) -> list[str]
   - [other field-specific extractors]

3. Validation and error handling

4. Type hints and docstrings

Ensure the code is:
- Deterministic (same input = same output)
- Efficient (regexes are pre-compiled)
- Safe (no eval, exec, or file operations)
- Testable (pure functions)

Return ONLY valid Python code that can be exec()'d directly."""

    try:
        code = llm.generate(
            prompt=user_prompt,
            system_prompt=system_prompt,
            temperature=0.0,
            max_tokens=4000
        )

        # Validate generated code
        code_hash = hashlib.sha256(code.encode()).hexdigest()

        return {
            "status": "success",
            "code": code,
            "code_hash": code_hash,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "model": config.VLLM_MODEL,
            "analysis": analysis
        }
    except Exception as e:
        logger.error(f"Code generation failed: {e}")
        return {
            "status": "error",
            "error": str(e)
        }


def save_extractor(extractor_data: Dict[str, Any],
                   version: str = "1.0",
                   output_dir: str = None) -> str:
    """Save generated extractor code to file.

    Args:
        extractor_data: Output from generate_extractors()
        version: Version string for this extractor
        output_dir: Directory to save to (default: GCS artifacts)

    Returns:
        Path/URI where extractor was saved
    """
    if extractor_data.get("status") != "success":
        raise ValueError(f"Cannot save failed extractor: {extractor_data.get('status')}")

    code = extractor_data.get("code")
    code_hash = extractor_data.get("code_hash")

    # Add header with metadata
    header = f'''"""Auto-generated extraction code - DO NOT EDIT MANUALLY

Generated: {extractor_data.get('generated_at')}
Model: {extractor_data.get('model')}
Code Hash: {code_hash}
Version: {version}

This code was generated by Phase 1 of the agentic extraction pipeline.
It has been validated by Phase 2 safety checks before execution.
"""
import re
import json
from typing import Dict, List, Optional, Any

'''

    full_code = header + code

    # If local directory specified, save there
    if output_dir:
        import os
        os.makedirs(output_dir, exist_ok=True)
        path = os.path.join(output_dir, f"extractors_v{version}.py")
        with open(path, "w") as f:
            f.write(full_code)
        logger.info(f"Saved extractor to {path}")
        return path

    # Otherwise, return code for GCS upload (Phase 4 will handle)
    return full_code
